# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/whb/.local/lib/python3.6/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/whb/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/vda3/test_netconf/openil_1028/output/build/qoriq-sysrepo-tsn-v0.2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/vda3/test_netconf/openil_1028/output/build/qoriq-sysrepo-tsn-v0.2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@echo "Installing the project stripped..."
	/home/whb/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@echo "Installing the project stripped..."
	/home/whb/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@echo "Installing only the local directory..."
	/home/whb/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@echo "Installing only the local directory..."
	/home/whb/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@echo "Install the project..."
	/home/whb/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@echo "Install the project..."
	/home/whb/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@echo "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@echo "Running CMake to regenerate build system..."
	/home/whb/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@echo "No interactive CMake dialog available..."
	/home/whb/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/vda3/test_netconf/openil_1028/output/build/qoriq-sysrepo-tsn-v0.2/CMakeFiles /mnt/vda3/test_netconf/openil_1028/output/build/qoriq-sysrepo-tsn-v0.2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/vda3/test_netconf/openil_1028/output/build/qoriq-sysrepo-tsn-v0.2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sysrepo-tsn

# Build rule for target.
sysrepo-tsn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sysrepo-tsn
.PHONY : sysrepo-tsn

# fast build rule for target.
sysrepo-tsn/fast:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/build
.PHONY : sysrepo-tsn/fast

src/brtc_cfg.o: src/brtc_cfg.c.o

.PHONY : src/brtc_cfg.o

# target to build an object file
src/brtc_cfg.c.o:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/brtc_cfg.c.o
.PHONY : src/brtc_cfg.c.o

src/brtc_cfg.i: src/brtc_cfg.c.i

.PHONY : src/brtc_cfg.i

# target to preprocess a source file
src/brtc_cfg.c.i:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/brtc_cfg.c.i
.PHONY : src/brtc_cfg.c.i

src/brtc_cfg.s: src/brtc_cfg.c.s

.PHONY : src/brtc_cfg.s

# target to generate assembly for a file
src/brtc_cfg.c.s:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/brtc_cfg.c.s
.PHONY : src/brtc_cfg.c.s

src/cb_streamid.o: src/cb_streamid.c.o

.PHONY : src/cb_streamid.o

# target to build an object file
src/cb_streamid.c.o:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/cb_streamid.c.o
.PHONY : src/cb_streamid.c.o

src/cb_streamid.i: src/cb_streamid.c.i

.PHONY : src/cb_streamid.i

# target to preprocess a source file
src/cb_streamid.c.i:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/cb_streamid.c.i
.PHONY : src/cb_streamid.c.i

src/cb_streamid.s: src/cb_streamid.c.s

.PHONY : src/cb_streamid.s

# target to generate assembly for a file
src/cb_streamid.c.s:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/cb_streamid.c.s
.PHONY : src/cb_streamid.c.s

src/common.o: src/common.c.o

.PHONY : src/common.o

# target to build an object file
src/common.c.o:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/common.c.o
.PHONY : src/common.c.o

src/common.i: src/common.c.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.c.i:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/common.c.i
.PHONY : src/common.c.i

src/common.s: src/common.c.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.c.s:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/common.c.s
.PHONY : src/common.c.s

src/file_mon.o: src/file_mon.c.o

.PHONY : src/file_mon.o

# target to build an object file
src/file_mon.c.o:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/file_mon.c.o
.PHONY : src/file_mon.c.o

src/file_mon.i: src/file_mon.c.i

.PHONY : src/file_mon.i

# target to preprocess a source file
src/file_mon.c.i:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/file_mon.c.i
.PHONY : src/file_mon.c.i

src/file_mon.s: src/file_mon.c.s

.PHONY : src/file_mon.s

# target to generate assembly for a file
src/file_mon.c.s:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/file_mon.c.s
.PHONY : src/file_mon.c.s

src/ip_cfg.o: src/ip_cfg.c.o

.PHONY : src/ip_cfg.o

# target to build an object file
src/ip_cfg.c.o:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/ip_cfg.c.o
.PHONY : src/ip_cfg.c.o

src/ip_cfg.i: src/ip_cfg.c.i

.PHONY : src/ip_cfg.i

# target to preprocess a source file
src/ip_cfg.c.i:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/ip_cfg.c.i
.PHONY : src/ip_cfg.c.i

src/ip_cfg.s: src/ip_cfg.c.s

.PHONY : src/ip_cfg.s

# target to generate assembly for a file
src/ip_cfg.c.s:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/ip_cfg.c.s
.PHONY : src/ip_cfg.c.s

src/mac_cfg.o: src/mac_cfg.c.o

.PHONY : src/mac_cfg.o

# target to build an object file
src/mac_cfg.c.o:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/mac_cfg.c.o
.PHONY : src/mac_cfg.c.o

src/mac_cfg.i: src/mac_cfg.c.i

.PHONY : src/mac_cfg.i

# target to preprocess a source file
src/mac_cfg.c.i:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/mac_cfg.c.i
.PHONY : src/mac_cfg.c.i

src/mac_cfg.s: src/mac_cfg.c.s

.PHONY : src/mac_cfg.s

# target to generate assembly for a file
src/mac_cfg.c.s:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/mac_cfg.c.s
.PHONY : src/mac_cfg.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/main.c.s
.PHONY : src/main.c.s

src/qbu.o: src/qbu.c.o

.PHONY : src/qbu.o

# target to build an object file
src/qbu.c.o:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qbu.c.o
.PHONY : src/qbu.c.o

src/qbu.i: src/qbu.c.i

.PHONY : src/qbu.i

# target to preprocess a source file
src/qbu.c.i:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qbu.c.i
.PHONY : src/qbu.c.i

src/qbu.s: src/qbu.c.s

.PHONY : src/qbu.s

# target to generate assembly for a file
src/qbu.c.s:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qbu.c.s
.PHONY : src/qbu.c.s

src/qbv.o: src/qbv.c.o

.PHONY : src/qbv.o

# target to build an object file
src/qbv.c.o:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qbv.c.o
.PHONY : src/qbv.c.o

src/qbv.i: src/qbv.c.i

.PHONY : src/qbv.i

# target to preprocess a source file
src/qbv.c.i:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qbv.c.i
.PHONY : src/qbv.c.i

src/qbv.s: src/qbv.c.s

.PHONY : src/qbv.s

# target to generate assembly for a file
src/qbv.c.s:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qbv.c.s
.PHONY : src/qbv.c.s

src/qci.o: src/qci.c.o

.PHONY : src/qci.o

# target to build an object file
src/qci.c.o:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qci.c.o
.PHONY : src/qci.c.o

src/qci.i: src/qci.c.i

.PHONY : src/qci.i

# target to preprocess a source file
src/qci.c.i:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qci.c.i
.PHONY : src/qci.c.i

src/qci.s: src/qci.c.s

.PHONY : src/qci.s

# target to generate assembly for a file
src/qci.c.s:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qci.c.s
.PHONY : src/qci.c.s

src/qci_fm.o: src/qci_fm.c.o

.PHONY : src/qci_fm.o

# target to build an object file
src/qci_fm.c.o:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qci_fm.c.o
.PHONY : src/qci_fm.c.o

src/qci_fm.i: src/qci_fm.c.i

.PHONY : src/qci_fm.i

# target to preprocess a source file
src/qci_fm.c.i:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qci_fm.c.i
.PHONY : src/qci_fm.c.i

src/qci_fm.s: src/qci_fm.c.s

.PHONY : src/qci_fm.s

# target to generate assembly for a file
src/qci_fm.c.s:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qci_fm.c.s
.PHONY : src/qci_fm.c.s

src/qci_sf.o: src/qci_sf.c.o

.PHONY : src/qci_sf.o

# target to build an object file
src/qci_sf.c.o:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qci_sf.c.o
.PHONY : src/qci_sf.c.o

src/qci_sf.i: src/qci_sf.c.i

.PHONY : src/qci_sf.i

# target to preprocess a source file
src/qci_sf.c.i:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qci_sf.c.i
.PHONY : src/qci_sf.c.i

src/qci_sf.s: src/qci_sf.c.s

.PHONY : src/qci_sf.s

# target to generate assembly for a file
src/qci_sf.c.s:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qci_sf.c.s
.PHONY : src/qci_sf.c.s

src/qci_sg.o: src/qci_sg.c.o

.PHONY : src/qci_sg.o

# target to build an object file
src/qci_sg.c.o:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qci_sg.c.o
.PHONY : src/qci_sg.c.o

src/qci_sg.i: src/qci_sg.c.i

.PHONY : src/qci_sg.i

# target to preprocess a source file
src/qci_sg.c.i:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qci_sg.c.i
.PHONY : src/qci_sg.c.i

src/qci_sg.s: src/qci_sg.c.s

.PHONY : src/qci_sg.s

# target to generate assembly for a file
src/qci_sg.c.s:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/qci_sg.c.s
.PHONY : src/qci_sg.c.s

src/vlan_cfg.o: src/vlan_cfg.c.o

.PHONY : src/vlan_cfg.o

# target to build an object file
src/vlan_cfg.c.o:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/vlan_cfg.c.o
.PHONY : src/vlan_cfg.c.o

src/vlan_cfg.i: src/vlan_cfg.c.i

.PHONY : src/vlan_cfg.i

# target to preprocess a source file
src/vlan_cfg.c.i:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/vlan_cfg.c.i
.PHONY : src/vlan_cfg.c.i

src/vlan_cfg.s: src/vlan_cfg.c.s

.PHONY : src/vlan_cfg.s

# target to generate assembly for a file
src/vlan_cfg.c.s:
	$(MAKE) -f CMakeFiles/sysrepo-tsn.dir/build.make CMakeFiles/sysrepo-tsn.dir/src/vlan_cfg.c.s
.PHONY : src/vlan_cfg.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sysrepo-tsn"
	@echo "... src/brtc_cfg.o"
	@echo "... src/brtc_cfg.i"
	@echo "... src/brtc_cfg.s"
	@echo "... src/cb_streamid.o"
	@echo "... src/cb_streamid.i"
	@echo "... src/cb_streamid.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/file_mon.o"
	@echo "... src/file_mon.i"
	@echo "... src/file_mon.s"
	@echo "... src/ip_cfg.o"
	@echo "... src/ip_cfg.i"
	@echo "... src/ip_cfg.s"
	@echo "... src/mac_cfg.o"
	@echo "... src/mac_cfg.i"
	@echo "... src/mac_cfg.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/qbu.o"
	@echo "... src/qbu.i"
	@echo "... src/qbu.s"
	@echo "... src/qbv.o"
	@echo "... src/qbv.i"
	@echo "... src/qbv.s"
	@echo "... src/qci.o"
	@echo "... src/qci.i"
	@echo "... src/qci.s"
	@echo "... src/qci_fm.o"
	@echo "... src/qci_fm.i"
	@echo "... src/qci_fm.s"
	@echo "... src/qci_sf.o"
	@echo "... src/qci_sf.i"
	@echo "... src/qci_sf.s"
	@echo "... src/qci_sg.o"
	@echo "... src/qci_sg.i"
	@echo "... src/qci_sg.s"
	@echo "... src/vlan_cfg.o"
	@echo "... src/vlan_cfg.i"
	@echo "... src/vlan_cfg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

